### ISSUE TITLE
发行版里添加编译后的apk

### ISSUE THREAD

**Issue by HimekoX** [StarWishsama/Nameless-Bot#101]
发行里加上编译结果 可以降低体验门槛233333

**Comment by StarWishsama** [comment]
apk？？？？

**Comment by HimekoX** [comment]
这难道不是安卓项目文件吗 23333（说错话请原谅菜逼）

Name1ess. <notifications@github.com> 于2020年10月6日周二 下午11:41写道：

**Comment by StarWishsama** [comment]
这又不是给安卓用的
