### ISSUE TITLE
/help指令无法一次性显示出所有菜单

### ISSUE THREAD

**Issue by aurorataro** [StarWishsama/Nameless-Bot#103]
## 描述 (必须)

/help指令无法一次性显示出所有菜单

## 复现步骤 (必须)

![image](https://user-images.githubusercontent.com/62366575/96216960-29845380-0fb4-11eb-9362-42fa014e9fc6.png)
如图 多余的菜单被省略号代替

## Log / Comet-Bot 的报错

无

## 使用环境 (必须)

树莓派 

 - Java 版本:pi@Raspberry:~ $ java -version
openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment (build 11.0.8+10-post-Raspbian-1deb10u1)
OpenJDK Server VM (build 11.0.8+10-post-Raspbian-1deb10u1, mixed mode)

 - Comet-Bot 版本: 0.6M1

**Comment by StarWishsama** [comment]
这是刻意设计的，为了防止刷屏。
计划修改为只显示命令名称，查看详细帮助则需要 /help 命令名

**Comment by aurorataro** [comment]
> 这是刻意设计的，为了防止刷屏。
> 计划修改为只显示命令名称，查看详细帮助则需要 /help 命令名

感谢reply  如果是这样的话  我认为可以的在readme里添加一些主要指令  作为一个临时的解决方案
