### ISSUE TITLE
bili info无法获取up的纯文字动态

### ISSUE THREAD

**Issue by Damonlove** [StarWishsama/Nameless-Bot#108]
bili info无法获取up的纯文字动态

**Comment by StarWishsama** [comment]
来个动态链接复现一下 有没有错误报告生成

**Comment by Damonlove** [comment]
> 来个动态链接复现一下 有没有错误报告生成

emm不是很懂代码，但是具体情况是这样的，下为图片左边是刚发的纯文字动态，右侧为群机器人测试http://r.photo.store.qq.com/psc?/V52mQkxV3Bn8GT1ztpFM2CoBem1Vu9CX/45NBuzDIW489QBoVep5mcdzJv9l0cwJXxP2VCN1EjkAWeGNKrqlk.P6s.QinESn22inNsujNp1X3ZxofydLyIPdfGYhZiZWQB5VMV6j2qKI!/r&save=1&d=1

**Comment by StarWishsama** [comment]
> > 来个动态链接复现一下 有没有错误报告生成
> 
> emm不是很懂代码，但是具体情况是这样的，下为图片左边是刚发的纯文字动态，右侧为群机器人测试http://r.photo.store.qq.com/psc?/V52mQkxV3Bn8GT1ztpFM2CoBem1Vu9CX/45NBuzDIW489QBoVep5mcdzJv9l0cwJXxP2VCN1EjkAWeGNKrqlk.P6s.QinESn22inNsujNp1X3ZxofydLyIPdfGYhZiZWQB5VMV6j2qKI!/r&save=1&d=1
> 

？跟懂不懂代码什么关系 哪条动态加载不了发个链接

**Comment by Damonlove** [comment]
> > > 来个动态链接复现一下 有没有错误报告生成
> > 
> > 
> > emm不是很懂代码，但是具体情况是这样的，下为图片左边是刚发的纯文字动态，右侧为群机器人测试http://r.photo.store.qq.com/psc?/V52mQkxV3Bn8GT1ztpFM2CoBem1Vu9CX/45NBuzDIW489QBoVep5mcdzJv9l0cwJXxP2VCN1EjkAWeGNKrqlk.P6s.QinESn22inNsujNp1X3ZxofydLyIPdfGYhZiZWQB5VMV6j2qKI!/r&save=1&d=1
> 
> ？跟懂不懂代码什么关系 哪条动态加载不了发个链接

https://t.bilibili.com/450700815639821202?tab=2

**Comment by StarWishsama** [comment]
> > > > 来个动态链接复现一下 有没有错误报告生成
> > > 
> > > 
> > > emm不是很懂代码，但是具体情况是这样的，下为图片左边是刚发的纯文字动态，右侧为群机器人测试http://r.photo.store.qq.com/psc?/V52mQkxV3Bn8GT1ztpFM2CoBem1Vu9CX/45NBuzDIW489QBoVep5mcdzJv9l0cwJXxP2VCN1EjkAWeGNKrqlk.P6s.QinESn22inNsujNp1X3ZxofydLyIPdfGYhZiZWQB5VMV6j2qKI!/r&save=1&d=1
> > 
> > ？跟懂不懂代码什么关系 哪条动态加载不了发个链接
> 
> https://t.bilibili.com/450700815639821202?tab=2

404 是不是删掉了

**Comment by Damonlove** [comment]
> > > > > 来个动态链接复现一下 有没有错误报告生成
> > > > 
> > > > 
> > > > emm不是很懂代码，但是具体情况是这样的，下为图片左边是刚发的纯文字动态，右侧为群机器人测试http://r.photo.store.qq.com/psc?/V52mQkxV3Bn8GT1ztpFM2CoBem1Vu9CX/45NBuzDIW489QBoVep5mcdzJv9l0cwJXxP2VCN1EjkAWeGNKrqlk.P6s.QinESn22inNsujNp1X3ZxofydLyIPdfGYhZiZWQB5VMV6j2qKI!/r&save=1&d=1
> > > 
> > > 
> > > ？跟懂不懂代码什么关系 哪条动态加载不了发个链接
> > 
> > 
> > https://t.bilibili.com/450700815639821202?tab=2
> 
> 404 是不是删掉了

对不起不小心给删了，这个没删https://t.bilibili.com/451098568270468043?tab=2

**Comment by StarWishsama** [comment]
在机器人运行路径下 error-reports 文件夹有没有文件？如果文件名有含 biilbili 字样的可以发上来

**Comment by StarWishsama** [comment]
已确认。
