### ISSUE TITLE
猜拳功能问题

### ISSUE THREAD

**Issue by AnotiaWang** [StarWishsama/Nameless-Bot#112]
## 描述 (必须)

发送 `/janken` 并出了一个拳头，然后机器人报错
应该是因为没有创建 /res/img 文件夹并写入图片（**我是从0.6-M1升级上来的**）

## 复现步骤 (必须)

![549ea51302212eb2.png](https://user-images.githubusercontent.com/62269186/98628833-6abd1880-2352-11eb-9b50-a0b32d9abf7e.png)

## Log / Comet-Bot 的报错

```
Bot > 在试图执行命令时发生了一个错误
简易报错信息 (如果有的话):
IllegalArgumentException:file /www/wwwroot/cometbot/res/img/rock.png is not readable
```

## 使用环境 (必须)

 - Java 版本:jre8
 - Comet-Bot 版本:0.6-M2

**Comment by StarWishsama** [comment]
测试过 JRE 8 不会生成资源文件 #91

**Comment by AnotiaWang** [comment]
原来如此😂已经解决了，谢谢

**Comment by StarWishsama** [comment]
有问题也可以加入交流群讨论：725656262
