### ISSUE TITLE
「功能请求」新增视频下载功能（基于youtube-dl）

### ISSUE THREAD

**Issue by AnotiaWang** [StarWishsama/Nameless-Bot#120]
- [x] 我已确认自己在反复寻找后没有发现已有相似功能
- [x] 我已确认该特性不与其他 Issues 撞车

## 新功能描述 (必须)

[ytdl-org/youtube-dl](https://github.com/ytdl-org/youtube-dl)

一个 Python 项目，支持绝大部分主流视频网站，包括油管、bilibili等，实测有效

能不能把这个做成插件呢？要求用户事先安装环境和youtube-dl

**Comment by StarWishsama** [comment]
可能不会加入。

1. 既然是下载视频，那么下载到哪里呢？又怎么返回给调用的用户呢？

2. > 要求用户事先安装环境和youtube-dl

目前需要额外安装环境的功能暂时不会考虑, 比如 #102

**Comment by AnotiaWang** [comment]
下载到一个临时文件夹，比如运行命令 `youtube-dl --output "/www/wwwroot/temp/%(title)s.%(ext)s" -f best https://b23.tv/pxjAqb `，以最高画质下载，并保存到 wwwroot/temp 目录下
至于怎么发送嘛……不知道 Mirai 有没有这个功能
