### ISSUE TITLE
「功能请求」关键词回复

### ISSUE THREAD

**Issue by AnotiaWang** [StarWishsama/Nameless-Bot#122]
- [x] 我已确认自己在反复寻找后没有发现已有相似功能
- [x] 我已确认该特性不与其他 Issues 撞车

## 新功能描述 (必须)
检测到关键词回复特定消息

**Comment by StarWishsama** [comment]
# 关键词回复

## 特性
- [x] 分群聊的关键词检测
- [ ] 支持字符匹配和正则匹配
