### ISSUE TITLE
积分用途

### ISSUE THREAD

**Issue by RedCarl** [StarWishsama/Nameless-Bot#142]
- [x] 我已确认自己在反复寻找后没有发现已有相似功能
- [x] 我已确认该特性不与其他 Issues 撞车

## 新功能描述 (必须)
签到后获得的积分现在很无用,我推荐出以下功能.

1.积分排名:对积分有一个排名,可以使用指令查询积分前10或者前5的群员
2.积分商城:利用 rCon 功能 可以实现使用积分兑换游戏商品,比如Minecraft,实现积分兑换然后后台执行指令,并扣除积分.(前提可能要做一个游戏ID绑定的功能,就可以将游戏的ID和当前QQ号绑定)
3.积分抽奖:可以使用积分进行抽奖,抽奖内容由群主自定义,可以是游戏道具,或者是积分,或者是群头衔之类的(如果可以更改)

**Comment by StarWishsama** [comment]
1. 已有 /info ph
2. HTTP-API 版本曾经做过, 现在在弃用状态
3. 抽奖 /roll，但是暂时不支持赠送特殊物品，需要等背包功能实装。
