### ISSUE TITLE
登录时提示当前版本过低， 请升级到QQ最新版本。

### ISSUE THREAD

**Issue by bowencraft** [StarWishsama/Nameless-Bot#160]
## 描述
登录账号时，输完验证码登录时候返回
`Recv: Error(title=温馨提示, message=当前版本过低， 请升级到QQ最新版本。, errorInfo=)`
![image](https://user-images.githubusercontent.com/34801660/106353634-daa0c680-62e3-11eb-9d0f-2e3b43a92d87.png)
登录失败

## 复现步骤
编译，java -jar ./build/libs/Comet-0.6.1-dev--all.jar 启动bot，
登录账号，输入密码，显示`Recv: Error(title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用设备上登录或稍后再试。, errorInfo=)`
重新输入密码和验证码，显示当前版本过低

## Log / Comet-Bot 的报错
[log-2021-01-30-18-19-36.log](https://github.com/StarWishsama/Comet-Bot/files/5897751/log-2021-01-30-18-19-36.log)
log文件

## 使用环境 (必须)
CentOS Linux release 7.6.1810

 - Java 版本: 
java version "1.8.0_231"
Java(TM) SE Runtime Environment (build 1.8.0_231-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.231-b11, mixed mode)

 - Comet-Bot 版本: Comet-Bot-0.6.1-dev-bcaca30
 - 我也尝试过stable版本 也是同样错误

**Comment by StarWishsama** [comment]
无法复现 登录问题请移步 mirai
