### ISSUE TITLE
启动时无法处理本地化字符串

### ISSUE THREAD

**Issue by Lynricsy** [StarWishsama/Nameless-Bot#177]
## 描述 (必须)
无法登录

## 复现步骤 (必须)
就是正常输入账号密码之后输入验证码

## Log / Comet-Bot 的报错
 Recv: Error(title=禁止登录, message=当前上网环境异常，请更换网络环境或在常用
设备上登录或稍后再试。, errorInfo=)

## 使用环境 (必须)
Windows10，19042.789

 - Java 版本:java1.8.0_281
 - Comet-Bot 版本:Comet-0.6.0-all

**Comment by StarWishsama** [comment]
可以试着更换协议到 ANDROID_PHONE
在配置文件里修改

**Comment by Lynricsy** [comment]
> 可以试着更换协议到 ANDROID_PHONE
> 在配置文件里修改

我试试

**Comment by Lynricsy** [comment]
2021-02-07 10:38:00 I/CometBot: 登录中... 使用协议 ANDROID_PHONE
2021-02-07 10:38:00 I/Comet 2188955531: Logging in...
2021-02-07 10:38:00 I/CometNet 2188955531: Connected to server 125.94.60.146:80
2021-02-07 10:38:00 V/CometNet 2188955531: Send: wtlogin.login
2021-02-07 10:38:00 V/CometNet 2188955531: Recv: LoginPacketResponse.Captcha.Slider
2021-02-07 10:38:00 I/CometNet 2188955531: Connected to server 125.94.60.146:80
2021-02-07 10:38:00 V/CometNet 2188955531: Send: wtlogin.login
2021-02-07 10:38:00 V/CometNet 2188955531: Recv: LoginPacketResponse.Captcha.Slider
2021-02-07 10:38:00 I/CometService: 登录失败, 如果是密码错误, 请重新输入密码
没有错误信息

**Comment by StarWishsama** [comment]
https://github.com/StarWishsama/Comet-Bot/actions/runs/544671963
试一下这个版本, Artifacts 下面下载

**Comment by Lynricsy** [comment]
Mirai 无法完成滑块验证. 使用协议 ANDROID_PHONE 强制要求滑块验证, 请更换协议后重试.

**Comment by StarWishsama** [comment]
> Mirai 无法完成滑块验证. 使用协议 ANDROID_PHONE 强制要求滑块验证, 请更换协议后重试.

更改协议为 ANDROID_PHONE，并使用 https://github.com/project-mirai/mirai-login-solver-selenium

**Comment by Lynricsy** [comment]
怎么用啊？

**Comment by StarWishsama** [comment]
> 怎么用啊？

如果不会使用，可以尝试将协议修改为 ANDROID_PAD。如果仍然提示需要滑块验证，请按照 https://github.com/project-mirai/mirai-login-solver-selenium#%E6%89%8B%E5%8A%A8%E5%AE%8C%E6%88%90%E6%BB%91%E5%8A%A8%E9%AA%8C%E8%AF%81 进行操作。

**Comment by Lynricsy** [comment]
添加参数好像无效……

**Comment by Lynricsy** [comment]
谢谢，手动获取ticket登录成功了。

**Comment by Lynricsy** [comment]
但是每次启动都会加载配置文件失败
2021-02-07 19:48:58 W/CometService: 加载配置文件失败, 部分配置文件将会立即创建备份
, 错误报告已生成! 保存在 D:\Documents\Qbot\error-reports\resource-2021-02-07-19-48-58.txt

发生了一个错误:
========================= 栈轨迹 =========================
异常类型 ▶
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 8 path $


包名 com.google ▶
  ▶ 在类 JsonParser, 方法 parseReader. (JsonParser.java, 行 66)
  ▶ 在类 JsonParser, 方法 parseString. (JsonParser.java, 行 47)

包名 io.github.starwishsama.comet ▶
  ▶ 在类 DataSetup, 方法 loadLang. (DataSetup.kt, 行 154)
  ▶ 在类 DataSetup, 方法 load. (DataSetup.kt, 行 87)
  ▶ 在类 DataSetup, 方法 init. (DataSetup.kt, 行 55)

包名 io.github.starwishsama ▶
  ▶ 在类 CometKt, 方法 initResources. (Comet.kt, 行 283)
  ▶ 在类 Comet, 方法 main. (Comet.kt, 行 69)
========================= 栈轨迹 =========================

可能有用的信息: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 8 path $

原始获取内容:
