### ISSUE TITLE
.gh 支持仓库名通配符

### ISSUE THREAD

**Issue by qianjunakasumi** [StarWishsama/Nameless-Bot#207]
- [x] 我已确认自己在反复寻找后没有发现已有相似功能
- [x] 我已确认该特性不与其他 Issues 撞车

## 新功能描述 (必须)

.github 功能支持仓库名的通配

例如

```
.gh add qianjunakasumi/*
```
可以推送 qianjunakasumi 下的所有仓库动态

**Comment by StarWishsama** [comment]
需要调用 Github API，考虑到会吃 API 限额，暂不考虑
