### ISSUE TITLE
rcon功能如何使用？

### ISSUE THREAD

**Issue by KokuraSona** [StarWishsama/Nameless-Bot#298]
## 问题 (必须)

如题，在config.yml配置完rcon后，机器人只对/rcon命令响应，根据回复的提示，输入/rcon setup无响应。

**Comment by KokuraSona** [comment]
> ## 问题 (必须)
> 如题，在 config.yml 配置完 rcon 后，机器人只对 /rcon 命令响应，根据回复的提示，输入 /rcon setup 无响应。

以及rcon指令的具体命令格式是什么？提示给的是“/rcon cmd/exec(命令)”，没有理解是将cmd/exec替换成对应的命令？还是说在括号内填写对应的命令？

**Comment by StarWishsama** [comment]
/rcon cmd/exec [你要输入的命令]

e.g.
`/rcon cmd/exec gc`

**Comment by StarWishsama** [comment]
已修复并更新对应帮助文本，请下载最新构建

**Comment by KokuraSona** [comment]
> 已修复并更新对应帮助文本，请下载最新构建

非常感谢！
但是在使用rcon连接到mc服务器的时仍然出现了问题，即mc服务器后台显示rcon已连接，但机器人依然提示rcon未设置，见下图。

<img width="565" alt="Screen Shot 2021-08-11 at 3 42 24 PM" src="https://user-images.githubusercontent.com/31174612/128989755-b15d33b5-94d8-44cb-8907-352f9c0a03a8.png">
<img width="304" alt="Screen Shot 2021-08-11 at 3 43 30 PM" src="https://user-images.githubusercontent.com/31174612/128990015-8a47ed88-0fed-4378-a23a-e3c924c6de1e.png">

**Comment by StarWishsama** [comment]
确定正确设置了 rcon 吗

**Comment by KokuraSona** [comment]
> 确定正确设置了 rcon 吗

从mc后台来看两者有建立连接，且端口号等设置一致，应该是没有问题的。

**Comment by StarWishsama** [comment]
有报错吗？

**Comment by KokuraSona** [comment]
> 有报错吗？

没有

**Comment by StarWishsama** [comment]
尝试重启一下 Bot

**Comment by KokuraSona** [comment]
> 尝试重启一下 Bot

重启后仍和之前一样，mc后台有rcon连接提示，但机器人端反馈rcon未设置。

**Comment by KokuraSona** [comment]
> 尝试重启一下 Bot
附上相关截图，另外，偶尔会出现如图中所示stop指令失效的情况。
<img width="724" alt="Screen Shot 2021-08-11 at 6 36 20 PM" src="https://user-images.githubusercontent.com/31174612/129015135-eac1cbf7-87fa-4755-98d5-c468f0f057d8.png">

**Comment by StarWishsama** [comment]
Try https://github.com/StarWishsama/Comet-Bot/runs/3299742210

**Comment by KokuraSona** [comment]
> Try https://github.com/StarWishsama/Comet-Bot/runs/3299742210

非常感谢🙏，上述两个问题均已得到解决。
