### ISSUE TITLE
安全问题：`gh` 命令可以产生未经授权的订阅

### ISSUE THREAD

**Issue by qianjunakasumi** [StarWishsama/Nameless-Bot#322]
## 描述 (必须)

可以为任何群订阅仓库更新，即使该群不存在。利用此可能产生安全问题，未经授权的访问、添加等

![image](https://user-images.githubusercontent.com/53565118/135210271-df030845-d00e-48af-b1e4-ebc364cd5cf5.png)

## 使用环境 (必须)

 - Java 版本:
 - Comet-Bot 版本:

**Comment by qianjunakasumi** [comment]
建议为群订阅仓库更新时，校验当前用户是否属于该群成员，该群是否存在。

还可以设置更精细的权限控制颗粒粒度，以防止未经授权的访问、更改

**Comment by qianjunakasumi** [comment]
利用此漏洞也能恶意删除别人订阅的仓库更新，暂无发现 secret 暴露风险

**Comment by StarWishsama** [comment]
在有命令对应权限条件下，默认为最高权限。

**Comment by StarWishsama** [comment]
- [x] 群订阅仓库更新时，校验当前用户是否属于该群成员，该群是否存在
- [ ] 更精细的权限控制颗粒粒度
