### ISSUE TITLE
将 Comet 的后台命令加入 Mirai-Console

### ISSUE THREAD

**Issue by Stardust-minus** [StarWishsama/Nameless-Bot#345]
## 问题 (必须)

Mirai版本 MiraiConsole v2.8.0-M1
JDK 11 CentOS 7.8
![image](https://user-images.githubusercontent.com/52093397/139521693-68329539-c02b-4321-9088-4aa344d7c516.png)
如图 默认情况下输出的是Mirai console 内置的指令。执行Comet的指令（例如bili login ）提示指令未知。
发送消息给Bot，Bot回复两条信息，一条是Comet的，一条是Mirai的。
![XWH7SA)H3UV$}LQUGPDX6)K](https://user-images.githubusercontent.com/52093397/139521732-67a5291c-25bc-4ef9-b4fb-23f8d59e3d57.png)
能否将Comet的指令整合进Mirai console的指令内，使得其可以遵循Mirai的权限管理，同时也方便执行某些指令呢？

**Comment by StarWishsama** [comment]
1. B站使用现在不再需要登录了
2. 与 Mirai Console 的整合不会立即完成

**Comment by StarWishsama** [comment]
已实现
