### ISSUE TITLE
[Rework] 重写文件存储位置获取

### ISSUE THREAD

**Issue by Colerar** [StarWishsama/Nameless-Bot#388]
- [X] 我已确认自己在反复寻找后没有发现已有相似功能
- [X] 我已确认该特性不与其他 Issues 撞车

## 新功能描述 (必须)

- 全局应该使用一个统一的 `resolveDataFile` 方法，而不是自行实现，这造成许多混乱，且不便于拓展。
- 允许在 IDE 环境和生产环境定义不同的文件存储行为。
- 允许用户手动指定存储路径（如通过类似 `-d` 的命令行参数选择存储文件夹）。

相关: #376

**Comment by StarWishsama** [comment]
~~允许用户手动指定存储路径（如通过类似 -d 的命令行参数选择存储文件夹）。~~
