### ISSUE TITLE
[Feature] 数据统计功能

### ISSUE THREAD

**Issue by WetABQ** [StarWishsama/Nameless-Bot#389]
- [x] 我已确认自己在反复寻找后没有发现已有相似功能
- [x] 我已确认该特性不与其他 Issues 撞车

## 新功能描述 (必须)

收集并统计机器人命令调用次数，生成趋势

**Comment by Colerar** [comment]
应该要等 #376 重构完成。

**Comment by StarWishsama** [comment]
除机器人命令调用次数以外，额外收集聊天记录生成词云。
