### ISSUE TITLE
Comet启动时报错

### ISSUE THREAD

**Issue by stars-spark** [StarWishsama/Nameless-Bot#402]
## 描述 (必须)
如题

## 复现步骤 (必须)
启动 ![IMG_20220623_122013.jpg](https://user-images.githubusercontent.com/53867496/175208393-8ce692d8-ce2d-47ce-b688-b35704b7b92e.jpg)

## 使用环境 (必须)

 - Java 版本:![IMG_20220623_122013.jpg](https://user-images.githubusercontent.com/53867496/175208340-6de41160-0cb0-41db-9f18-05dd2d56ba43.jpg)
 - Comet-Bot 版本:

**Comment by stars-spark** [comment]
版本0.6.6

**Comment by StarWishsama** [comment]
你语言文件放错地方了
