### ISSUE TITLE
执行/rcon命令时提示没有权限

### ISSUE THREAD

**Issue by stars-spark** [StarWishsama/Nameless-Bot#405]
## 问题 (必须)
![Screenshot_2022_0716_093353.jpg](https://user-images.githubusercontent.com/53867496/179329588-3d06a24b-7375-4d89-97cf-0d9329137712.jpg)

**Comment by StarWishsama** [comment]
后台给自己加 OWNER 权限

**Comment by stars-spark** [comment]
> OWNER
/permission还是config里设置
/permission我已经给了":"

**Comment by StarWishsama** [comment]
> > OWNER
> > /permission还是config里设置
> > /permission我已经给了":"

https://github.com/StarWishsama/Comet-Bot/wiki/%E5%90%8E%E5%8F%B0%E5%91%BD%E4%BB%A4#admin

给自己加 OWNER 权限组，Comet 目前并不支持通配符获取全部权限
