### ISSUE TITLE
[Feature] 希望对硬币多一些配置

### ISSUE THREAD

**Issue by NealLemonade** [StarWishsama/Nameless-Bot#514]
编程能力不是很强，但看到源码里有相关代码
希望可不可以有指令能增加/删除硬币；自定义每日范围一类的（我已在源码中略微理解但不太确定可以忽略此条）
感激不尽
好像我也不会自行构建这个...

**Comment by StarWishsama** [comment]
关于编译：https://github.com/StarWishsama/Comet-Bot/wiki/%E7%BC%96%E8%AF%91-Comet

**Comment by NealLemonade** [comment]
> 关于编译：https://github.com/StarWishsama/Comet-Bot/wiki/%E7%BC%96%E8%AF%91-Comet

感谢大佬

**Comment by NealLemonade** [comment]
> 关于编译：https://github.com/StarWishsama/Comet-Bot/wiki/%E7%BC%96%E8%AF%91-Comet

大佬这个owner要怎么添加啊，还有权限一类的，在源码里也看到了但没找到如何添加；顺便问一下有计划支持外部插件的想法吗（

**Comment by StarWishsama** [comment]
/promote [id] -p/--platform=[平台]

关于外部插件，暂时还没有

**Comment by NealLemonade** [comment]
> /promote [id] -p/--platform=[平台]
> 
> 关于外部插件，暂时还没有

（输入/硬币 /coin 就返回了这一条
命令 coin 执行状态 成功, 耗时 1毫秒 ）

不管添加什么都说 错误: 输入了多余的参数

（如果还是尚未完成 对不起打扰了！ 抱歉）

**Comment by StarWishsama** [comment]
/coin -t (目标用户, 不加该参数为自己) -d (增加的金币)
/coin -t (目标用户, 不加该参数为自己) -w (减少的金币)

使用 /coin -h 查看

**Comment by StarWishsama** [comment]
相关的新配置可以在 `./config/feature.yml` 看到。
