### ISSUE TITLE
导包显示错误

### ISSUE THREAD

**Issue by dfaofeng** [StarWishsama/Nameless-Bot#57]
![1](https://user-images.githubusercontent.com/14891398/84880867-add6d080-b0bf-11ea-806f-49859620f097.png)

![2](https://user-images.githubusercontent.com/14891398/84880871-af07fd80-b0bf-11ea-8bc5-cb8a8db95de0.png)项目初始化完成后显示这几个包好像没导入

**Comment by dfaofeng** [comment]
还发现了一个坑,这个打包好的不能用低于jdk11版本以下使用 ,最好在 readme中备注下...

**Comment by dfaofeng** [comment]
![QQ截图20200617174844](https://user-images.githubusercontent.com/14891398/84883168-ceecf080-b0c2-11ea-82a5-f82e0a4881e2.png)
登录已经完成后显示报错...

**Comment by StarWishsama** [comment]
本来这个项目是抱着自用的心态开发的，没怎么写readme（
这些问题会在明天看看的

**Comment by StarWishsama** [comment]
第二个导入的是我错误导入的包
第一个包试试更换repo吧 我本地是可以编译的
