### ISSUE TITLE
配置相关（管理员设置）

### ISSUE THREAD

**Issue by PoeraWork** [StarWishsama/Nameless-Bot#72]
请问如何设置管理员？
自己瞎整算是启动了bot，但是订阅v需要管理员权限，如何赋予用户管理员权限呢？又如何取消管理员权限呢？
PS：酷q停运，未来新人（比如我）可能会多点，求一份带注释的配置模板。

**Comment by StarWishsama** [comment]
订阅v不需要管理员权限啊 直接在 /bili 和 /twitter 命令下就行

**Comment by PoeraWork** [comment]
似乎不行，只会回Bot > 你没有权限

**Comment by StarWishsama** [comment]
好吧, 只有订阅开播状态才行, 设置机器人管理员稍后会添加
你还可以使用 /admin permadd [用户] nbot.commands.twitter 添加权限可以使用

**Comment by PoeraWork** [comment]
好的，辛苦了www

**Comment by StarWishsama** [comment]
配置模板: https://github.com/StarWishsama/Comet-Bot/wiki/%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6
临时摸了一个，之后会把配置文件换成更人性化一点的 YAML（

**Comment by PoeraWork** [comment]
感谢，就是主人那个选项填了似乎没用（指发布版本）

**Comment by StarWishsama** [comment]
收到，0.5修复。现在还在肝油管的直播推送
