### ISSUE TITLE
owner设置无效

### ISSUE THREAD

**Issue by sakurayun** [StarWishsama/Nameless-Bot#86]
## `owner`设置无效

使用：`releases`的0.5dev
用git指令恢复了之前的配置文件 `wiki` ，并按照之前的 `wiki` 配置 `config.yml`

配置为：`ownerId: 2063850823`

但在私聊的时候 `bot` 依旧提示：Bot > 你没有权限！

我想请问一下，我的 `owner` 的添加方式是否存在错误？
如果存在错误的话，我又该如何改正呢？

**Comment by StarWishsama** [comment]
收到，下个版本将会改进方式。以后将不再是在配置文件中设置，而是在后台命令中自行注册。

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by StarWishsama** [comment]
在后台中使用命令 `.admin setowner 你的QQ号`, 该QQ号所对应的机器人账号将会提升权限组为owner (需要使用 0.5.1+)
