### ISSUE TITLE
推送器在首次启动推送后不推送

### ISSUE THREAD

**Issue by StarWishsama** [StarWishsama/Nameless-Bot#93]
## 描述 (必须)

RT

## 复现步骤 (必须)

直接使用推送器

## Log / Comet-Bot 的报错

🈚

## 使用环境 (必须)

 - Java 版本: OpenJDK 11
 - Comet-Bot 版本: 0.3.6-200904

**Comment by StarWishsama** [comment]
也有可能是网络问题，只能在推文推送复现

**Comment by zipated** [comment]
复现

**Comment by StarWishsama** [comment]
> 复现

都有吗？还是只有推文

**Comment by StarWishsama** [comment]
Fixed

**Comment by StarWishsama** [comment]
偶尔还会丢，考虑删除火星推文检测，做火星Bot（

**Comment by StarWishsama** [comment]
测试机网络不太好，可能还是网络的锅

**Comment by StarWishsama** [comment]
Fixed on 0.6.0-M1
