### ISSUE TITLE
原神抽卡模拟器

### ISSUE THREAD

**Issue by StarWishsama** [StarWishsama/Nameless-Bot#95]
- [ ] 我已确认自己在反复寻找后没有发现已有相似功能
- [ ] 我已确认该特性不与其他 Issues 撞车

**Comment by StarWishsama** [comment]
lack of gacha pool data

**Comment by StarWishsama** [comment]
憨批米哈游

**Comment by Colerar** [comment]
@WetABQ Why do not commit and push?

**Comment by StarWishsama** [comment]
@WetABQ Why do not commit and push?

**Comment by WetABQ** [comment]
plz resolve the merge conflicts, I've updated on #387

**Comment by StarWishsama** [comment]
#387
